Updated besman role
Be-Secure/ansible-role-oah-bes pull request #4
Opened 2023-08-03 16:16 UTC by pramit-d

https://github.com/Be-Secure/ansible-role-oah-bes/issues/3

Fixed BeSman ansible role

2023-08-21 07:04 UTC, asa1997 requested changes
@pramit-d 
- BeSman is not getting installed.

2023-08-21 07:05 UTC, asa1997 commented on tasks/oah-install-besman.yml
Please move this code to oah-install.yml file. Same for other files as well.

2023-08-23 07:22 UTC, pramit-d commented on tasks/oah-install-besman.yml
As discussed, writing separate task files for every bes tool is required to maintain ansible-role-oah-bes.

2023-08-24 09:19 UTC, anilsingla approved these changes

2023-08-24 09:37 UTC, merged